image: python:3.11

variables:
  GIT_SUBMODULE_STRATEGY: recursive

pages:
  script:
    - pip install -r requirements.txt
    - pelican content/ -o public/ -s publishconf.py -D
  artifacts:
    paths:
      - public
