#+Title: Presentations
#+Date: 2017-Aug-23
#+Property: Summary List of presentations

This page hosts a list of html presentations that I've made. They're made using
[[https://github.com/hakimel/reveal.js/][reveal.js]]; you can navigate through using your arrow keys, make them full screen
by pressing your F key, and view any speaker notes by pressing S (they will open
as a pop-up). These seem to work best in Chrome or Chromium.

- [[file:{static}/presentations/CCN.Salon.2023-08-11.html][CCN Salon]] presentation. Introducing myself to the members of CCN.
- [[file:{static}/presentations/Thesis.Defense.2022-04-15-no-ackn.html][Thesis defense public talk]]. A video recording of this talk can be found [[https://archive.org/details/broderick_defense][on the
  Internet Archive]] (they'll host your stuff for free, forever). The presentation
  contains several very large images, so it may take a bit longer to load.
- [[file:{static}/presentations/1st-Year-Talk.2017-10-19.html][First Year Talk]] (note that there's an animated gif about half way
  through this presentation showing my experiment; it's slowed down
  but it involves rapidly flashing black and white gratings, so I'm
  slightly worried it could trigger seizures in people who are
  particularly photosensitive, so be aware).
- [[file:{static}/presentations/2017-07-24_lab_mtg.html][Overview of spatial frequency literature]]
- [[file:{static}/presentations/TheoNeuroJC.2017-04-20.html][Evolution and Vision]]
